# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NinerAlerts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'

  # Pods for NinerAlerts

  target 'NinerAlertsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NinerAlertsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
